services:
  panel:
    image: cyrusian/panel:latest
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /var/lib/cyrusian/panel:/var/lib/cyrusian/panel

  node:
    image: cyrusian/node:latest
    restart: always
    network_mode: host
    environment:
      SERVICE_ADDRESS: "127.0.0.1"
      INSECURE: "True"
      XRAY_EXECUTABLE_PATH: "/usr/local/bin/xray"
      XRAY_ASSETS_PATH: "/usr/local/lib/xray"
      XRAY_CONFIG_PATH: "/var/lib/cyrusian/node/xray_config.json"
      SSL_KEY_FILE: "./server.key"
      SSL_CERT_FILE: "./server.cert"
    volumes:
      - /var/lib/cyrusian/node:/var/lib/cyrusian/node
